INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Michael M.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-5-15', true, 'Site 1 - Redwood Camp', null, 'This was our third trip to Salmon Creek Ranch, and we had a wonderful time as always. Thank you for your wonderful hospitality.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Dan P.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-5-15', true, 'Site 2 - Creekside Camp', 'Creekside #2', 'I had a great time camping! Stayed at Creekside #2 and really enjoyed the experience.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Julie T.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/10102309938935784.jpg', '2023-5-15', true, 'Site 2 - Redwood Camp', 'Fun stay with little ones', 'Some friends and I brought our babies camping for the first time on John and Lesley’s land. It was a fantastic first camping experience for all of us! The farm itself is huge and very green. The kiddos enjoyed seeing the animals (dogs, ducks, and goats!). The campsite itself was big, clean, and had everything we needed (though make sure to bring your own water!). John was super friendly and a clear communicator. We also came home with some duck eggs, which we are excited to devour!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Emma M.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/4197022053724766.jpg', '2023-5-8', true, 'Eagle’s Nest Treehouse Farmstay', 'Great stay!', 'Lesley and John were lovely hosts. They are incredibly responsive and kindly showed us around the treehouse and answered questions about the property. Photos cannot do the treehouse justice. The craftsmanship and peaceful location are truly special.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Jessy K', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-5-7', true, 'Site 1 - Creekside Camp', 'Gem in the Redwoods', 'Beautiful location. Great to hear creek sounds all night. Secluded but accessible. The directions were very clear. Hiking around the property was lovely. This is a true gem of a site in the redwoods! We hope to return.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Karilyn O.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-5-2', false, 'Site 2 - Creekside Camp', null, 'Sadly we were pressed for time driving up from LA and since they have a must arrive before 9pm notice, we headed straight to the site not realizing that we were not near any food options that were still open. We survived, but I wish I had known in advance that they have a 9pm arrival time (although I’m sure we would have thought we would arrive early anyway!) The sites are located literally right on the road, just separated by a few plants and a fence. It’s a quiet road, but it does just feel like you are in some random overgrown area to be honest. We were in a 22 foot camper and it was tough to fit it well. We had to leave quite early in the morning and were shocked to see someone sleeping on the ground near the gate. It was a bit unnerving as we didn’t see a vehicle so weren’t sure if they were legally staying or not. This was our first time to do Hipcamp and we were a bit disappointed. Considering the price of this site, I’m not sure I would recommend as it’s quite pricey for what you get, unless this is your destination and you plan to hike around the property more…');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Inbal B.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/5195829463816594.jpg', '2023-5-2', true, 'Site 2 - Creekside Camp', 'beautiful campsite, part of nature!', 'Such a beautiful camp! Close enough to home (bay area folks), but totally secluded - a part of nature...John and Lesley were very responsive to my many questions, we were 4 families and camped along the meadow of combined campsites #1, #2, #3 - had the creek to ourseleves and overall a wonderful time. Take note there is no running water - literally - that is good for dishwashing/ hydrating. BYO. We will definitely come back!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Marilyn H.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-4-27', true, 'Eagle’s Nest Treehouse Farmstay', null, 'The treehouse was absolutely breathtaking! The bed was comfortable I didn’t want to get up. John and Leslie were perfect hosts 💞💞💞');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Karen J F.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-4-25', true, 'Eagle’s Nest Treehouse Farmstay', null, 'We THOROUGHLY LOVED our stay at Eagle’s Nest!!! Truly a dream come true staying in a treehouse and in such a beautiful setting surrounded by nature. We were welcomed into the world that John & Lesley created w their beautiful animals grazing the rolling pastures, the forest and the magical treehouse so perfectly placed to really commune w the natural world. SO PEACEFUL AND SERENE. HIGHLY RECOMMEND TO ANY AND ALL!!!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Inbal B.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/5195829463816594.jpg', '2023-4-23', true, 'Site 1 - Creekside Camp', null, 'So wonderful to have a group camp without anyone around us…. Definitely not the usual campsite — being it all with you, except the picnic table and fire pit :) Camped with 3 other families, all young children, we all had a wonderful and chill time. The creek is so full Post rains, and super clean too. John and Lesley answered all of my questions (I had many!). There isn’t reception for the most part, but all the instructions work as explained. Highly recommended- when you are ready to just be part of nature, this is the place to go! Thank you for letting our group on this well kept nature filled ranch');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Sheree W.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1679903399/profile/igg48vbztdb29a5er9hx.jpg', '2023-4-19', true, 'Site 3 - Redwood Camp', null, 'I booked my trip on a Monday so my friend, my 2 labs, and I had the whole place to ourselves. So much to love about this ranch with its extensive hiking trails and easy access to the creek. A few of the campsites are under the calm and solitude of redwood groves--definitely a relaxing getaway. Looking forward to returning during the summer.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Anthony R', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/10228088127285597.jpg', '2023-4-17', true, 'Site 1 - Redwood Camp', null, 'Camping at site #1 on John and Lesley’s land was wonderful. Driving in was a bit of an adventure but in a good way. Make sure to bring the 4wd :) You should definitely treat yourself with some of the goodies from the mercantile. We centered almost all of our meals on what was available at the mercantile. Having Filet Mignon and Duck eggs was a wonderful way to start off the day camping. When we went they had plenty of duck eggs and various cuts of beef and goat vacuum sealed in the deep freezer. The center meadow was perfect for stargazing but it gets a little damp with few so make sure to bring your boots. Near the entrance of the farm there is a family trout fishing farm. We didn’t catch anything(my 3yo daughter was more interested in casting and then reeling it in immediately haha) They gave us a free return ticket to use within 30 days. If you are planning to go, I would do it on the first day so that you can come back if you don’t catch anything. Most of all we just enjoyed hanging out under the beautiful redwoods. Not many other places where you can have 400 acres of pristine land to explore.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Alyssa E.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-4-14', true, 'Site 3 - Creekside Camp', 'Enchanting Creekside Retreat', 'Beautiful area. We had a great time! We stayed at Campsite 3 near the creek with our four kids ages 3 to 14. The trail down to the creek leads from the tent deck. It’s pretty steep—take caution. But the kids loved playing by the creek all day! There was a fire ring and a picnic table at the campsite. Bring your own firewood and especially kindling! We stayed in mid-April so it was cold at sunset. We layered up and wore beanies while we slept. But it was still super fun! We would definitely recommend to friends and would love to stay there again. There are an abundance of plants that surround the campsite that you should not touch, some type of nettle—so beware. Also, we got lost trying to find the campsites and had to turn around several times. Best advice—for Creekside campsites set your GPS directions from your starting point to take you to the BODEGA post office (Not Bodega Bay—no cell service in the Bodega area which added to our confusion.) Once you get to the post office, Salmon Creek road is directly across the street. Follow the Host’s written directions from there. Just after you cross the bridge there will be a gate on the left side for the 3 Creekside campsites. There is only one porta-potty for all three sites but it was clean and there was no smell. We were the only ones camping at the sites so it was nice and quiet. Loved the blue wildflowers and ferns. Felt like we were in a fairy forest. Definitely recommend!!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Michal R.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1620666176/profile/qxsjg0czzl8usnbqixur.jpg', '2023-4-9', true, 'Eagle’s Nest Treehouse Farmstay', 'Gorgeous treehouse right by coast', 'What an amazing location and treehouse! We spent the evening in the treehouse after a wonderful fish and chips dinner just ten minutes away on the coast, and loved waking up surrounded by ancient trees. The farm is gorgeous and the hosts are so nice!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Warren W.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-4-7', true, 'Site 3 - Creekside Camp', 'Gorgeous treehouse right by coast', 'I stayed in Creekside #3. It was closer to the road than I was expecting, but I don’t think I saw one car drive by the whole time. It was really close to the creek, which was great. There are tons of trails to hike on the other side of the creek.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Brian B.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1681533293/profile/ulbqw2e4yepokkrjvtjj.jpg', '2023-4-2', true, 'Eagle’s Nest Treehouse Farmstay', 'Waking up in the trees is magical!', 'John and Leslie’s land is a beautiful working ranch with lovely goats, cows and ducks, and the treehouse is absolutely magical. Only regret is not staying here for more than one night. We’ll have to come back soon!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Lauren J.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/1730579680292009.jpg', '2023-4-1', true, 'Eagle’s Nest Treehouse Farmstay', 'Perfect Treehouse Paradise', 'John and Lesley were amazing hosts. Our camper van we were traveling in would not make it down the road to the treehouse, so John graciously let us use his Subaru to make trips back and forth. The treehouse was a dream!! Waking up in the canopy of trees on our honeymoon road trip was definitely the highlight. We grilled up some delicious burgers fresh from their farm! Make sure to spend some time hiking the beautiful trails of John and Lesley’s perfect paradise.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Samantha T.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/1730579680292009.jpg', '2023-3-30', true, 'Eagle’s Nest Treehouse Farmstay', null, 'The eagle’s nest was so much fun! It was so relaxing sitting in the trees and listening to the rain, we even saw some deer right outside. John and Lesley were very helpful and friendly, but also let us enjoy our vacation without interruption. I can’t wait to come back!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Matthew L.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-3-18', true, 'Eagle’s Nest Treehouse Farmstay', 'Perfect romantic getaway', 'The eagle’s nest was so much fun! It was so relaxing sitting in the trees and listening to the rain, we even saw some deer right outside. John and Lesley were very helpful and friendly, but also let us enjoy our vacation without interruption. I can’t wait to come back!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Sahil S.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-3-12', true, 'Eagle’s Nest Treehouse Farmstay', 'Beautiful treehouse!', 'One of the best experience for me and my wife. Tree house is beautiful. Will recommend 100% to anyone.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Audrey C.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-2-28', true, 'Site 3 - Redwood Camp', 'Peaceful camping at its finest', 'This camping spot is absolutely perfect for someone looking for a peaceful private spot to camp. The sound of the rustling creek was amazing to fall asleep to. John was incredibly helpful at providing directions when we got lost trying to find his place. Highly recommend and will visit again if we are back in the area!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Kelly C.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-2-27', true, 'Site 1 - Redwood Camp', 'Camping in the wild!', 'Beautiful land wow! Camp 1 is a little darker in the redwoods and chilly so we chose to sleep in camp two that had sunshine and redwoods! Beauuuutiful! Recommend any of the camps, John was easy to work with. Delightful!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Isabel T.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-2-23', true, 'Site 2 - Redwood Camp', null, 'The ranch is absolutely gorgeous and really well -located near Bodega Bay, Dillon Beach, etc. We loved hiking around the property’s trails and find the beautiful Highland Cattle. Some things to keep in mind are that the meadow sites are not super accessible (you truly need AWD) and we weren’t comfortable driving the route at night so the convenience of car camping is reduced.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('James D.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-2-22', true, 'Eagle’s Nest Treehouse Farmstay', null, 'A magical location. Peaceful, beautiful, and safe. Lovely hosts! Dig the Mercantile too!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Hannah D.', 'https://hipcamp-res.cloudinary.com/image/upload/v1681428992/default_avatar_sxenbd.png', '2023-2-20', true, 'Site 1 - Redwood Camp', null, 'John and Lesley’s property is such a refreshing gem in California. It was a perfect starting point for our weekend backpacking trip in Point Reyes. Campsite 1 was a cozy redwood grove with a picnic table, a fire ring, and a nearby portojohn. We spent a few hours walking around the property to explore the trails and especially to see the animals. John was out and about and was so friendly. We loved talking to him about the animals and their land. The road down to camp is steep and rough, about 4-5mph careful drive with a high clearance car will do the trick. I would love to come back here again, great memories!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Brandi B.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1598835003/profile/aohdjfuyceyoxdnlxnch.jpg', '2023-2-20', true, 'Site 1 - Redwood Camp', 'Camp in the stars', 'John & Lesley are great hosts! They gave great directions and we loved the property! Oh, The stars! Great stay for the night.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Eric E.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/10221285787754122.jpg', '2023-2-19', true, 'Site 3 - Redwood Camp', 'Five stars', 'Had a really great time staying at the redwood camp. We stayed at campsite 3 and it is perfect if you’re looking for a weekend to disconnect. John was a really great host and even lended us jumper cables because I was an idiot and left the light on in my car all night. What a guy!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Meg S.', 'https://hipcamp-res.cloudinary.com/image/facebook/h_150,w_150/10214803459624974.jpg', '2023-1-3', true, 'Eagle’s Nest Treehouse Farmstay', null, 'This place is magical. I don’t think there’s anything new I can add to the other reviews on here - it is a very special place that I will never forget.');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Ashlyn R.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1655065027/profile/vn1kslymkjjetnltuwes.jpg', '2022-12-29', true, 'Eagle’s Nest Treehouse Farmstay', null, 'Another side of Bodega Bay I needed to see! Nestled in the amazing trees amongst the redwoods. Not hard to get to. Lesley met with me to get me to the treehouse. Really kind and showed me around. I was even able to explore more of the property and do some morning hiking. The morning fog from the ocean was a chef’s kiss. Hope to come back someday when I need a peaceful escape!');

INSERT INTO rating (username, pic_url, date, recommend, campsite, top_line, narrative) VALUES ('Bruce W.', 'https://hipcamp-res.cloudinary.com/image/upload/c_fill,f_auto,h_150,w_150/v1655065027/profile/vn1kslymkjjetnltuwes.jpg', '2022-12-29', true, 'Eagle’s Nest Treehouse Farmstay', 'So relaxing and secluded. Very 😍', 'It’s as though you’re going on to your own private ranch. Right away you see cattle and a little further on some veryFuzzy Furry cattle. Upon arriving at the main house and mercantile I was greeted by Leslie. I let her know what we preordered for food and she took me into the mercantile and showed me around and got us our food along with Some extra we decided to get. They even have dog treats made from their livestock. Next we were taken to the tree house not far away and given a walk through on how everything worked very beautiful tree house And a nice area to eat down below.');