INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Wildwood Retreat', 3, 'High', true, 'Escape to the serene Wildwood Retreat surrounded by lush greenery.', 4, 'No pets allowed', 'Fire pit, Picnic table', 50.00,'RV/tent site','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1447144043/campground-photos/deqddjjea4ilhirvyzai.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Serenity Springs', 3, 'Medium', true, 'Experience tranquility at Serenity Springs, where you can unwind and rejuvenate.', 6, 'Quiet hours between 10 PM and 7 AM', 'Hiking trails, Fishing spot', 60.00,'RV/tent site','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1447142515/campground-photos/rd7dvfnczgfeiehtabxm.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Whispering Pines', 6, 'Low', false, 'Discover the magic of Whispering Pines, surrounded by towering pine trees.', 3, NULL, 'Campfire ring, BBQ grill', 40.00,'Lodging','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1447813372/campground-photos/b67zkjgrdgim0zrwe1dp.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Mountain Vista', 3, 'High', true, 'Enjoy breathtaking views from Mountain Vista, where adventure awaits.', 8, 'No smoking allowed', 'Scenic overlook, Wildlife spotting', 75.00,'Lodging','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1447144254/campground-photos/hb94pn0mjd51zlnnl53w.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Lakeside Haven', 4, 'Medium', false, 'Experience serenity at Lakeside Haven, nestled by a pristine lake.', 5, 'Pets allowed on leash', 'Kayaking, Fishing dock', 55.00,'Lodging','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1541964948/campground-photos/wxy1q7nw0z6mtvxsscbi.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Tranquil Meadows', 6, 'High', true, 'Immerse yourself in the tranquility of nature at Tranquil Meadows.', 2, 'No loud music after 9 PM', 'Nature trails, Picnic area', 45.00,'RV/tent site','https://hipcamp-res.cloudinary.com/f_auto,c_limit,w_950,q_80/v1476481913/campground-photos/cype84jbmatzfgmae0vh.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Adventure Point', 3, 'High', true, 'Embark on an unforgettable adventure at Adventure Point, the ultimate outdoor playground.', 10, NULL, 'Rock climbing wall, Zipline', 80.00,'RV/tent site','https://explorerchick.com/wp-content/uploads/2019/02/Camping-in-lake-clark-national-park-women-only-copy-01.jpeg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Moonlit Grove', 2, 'Medium', false, 'Experience the enchantment of the Moonlit Grove, surrounded by ancient trees.', 4, NULL, 'Campfire circle, Stargazing platform', 60.00,'lodging','https://tpwd.texas.gov/state-parks/park-information/facilities/campsites/tpw_tof_003_800p.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Starry Skies Campground', 2, 'High', true, 'Camp under the starry skies at our enchanting campground.', 6, 'No RVs allowed', 'Firewood provided, Outdoor games', 65.00,'RV/tent site','https://cdn.vox-cdn.com/thumbor/wNCd1cBf7MrId4a_2IT-XmcfygY=/0x0:5114x3414/1200x800/filters:focal(2148x1298:2966x2116)/cdn.vox-cdn.com/uploads/chorus_image/image/64713096/shutterstock_1106746100.0.jpg');
INSERT INTO campsites (name, available, demand, instantBook, descriptions, capacity, restrictions, amenities, price, type,imgURL)
VALUES ('Rustic Oasis', 4, 'Medium', true, 'Escape to the Rustic Oasis, a hidden gem nestled in nature.', 3, NULL, 'Hammock, BBQ area', 50.00,'RV/tent site','https://sanctuaryhomedecor.com/wp-content/uploads/2021/06/Rustic-Built-In-BBQ-Area-6.jpg');
